"""empty message

Revision ID: 291e7f95b447
Revises: 
Create Date: 2020-07-29 09:16:49.048955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '291e7f95b447'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username'),
    sa.UniqueConstraint('username')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('mobile', sa.String(length=11), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('zipcode', sa.Integer(), nullable=True),
    sa.Column('primary_care_physician', sa.String(length=255), nullable=True),
    sa.Column('Secondary_doctor', sa.String(length=255), nullable=True),
    sa.Column('Hospital_name', sa.String(length=255), nullable=True),
    sa.Column('membership_level', sa.Integer(), nullable=True),
    sa.Column('subscription_to_alerts', sa.Boolean(), nullable=True),
    sa.Column('permission_for_doctor', sa.Boolean(), nullable=True),
    sa.Column('Health_conditions_of_interest', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=False),
    sa.Column('ownerid', sa.String(length=255), nullable=False),
    sa.Column('addeddate', sa.DATETIME(), nullable=False),
    sa.Column('specialization', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('subscription_to_alerts', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('Hospital_Affiliation', sa.String(length=255), nullable=False),
    sa.Column('Specialization', sa.String(length=255), nullable=False),
    sa.Column('affiliated_patients', sa.String(length=255), nullable=False),
    sa.Column('Baseline_rules', sa.String(length=255), nullable=False),
    sa.Column('contact_Number', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('doctor')
    op.drop_table('device')
    op.drop_table('User')
    op.drop_table('Admin')
    # ### end Alembic commands ###
